name: build-image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ramibenelmir
          password: ${{secrets.docker_hub_token}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ramibenelmir/CRV_TME8:1.0.0
